# Generated by Django 4.1.3 on 2022-12-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='seats',
            field=models.IntegerField(default=0),
        ),
    ]
